# .github/workflows/deploy.yml

name: Deploy to VPS

# This action runs on every push to the 'main' branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a fresh virtual machine for this job

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm use 20
          # Navigate to the project directory
          cd ${{ secrets.PROJECT_PATH }}
          
          # Pull the latest changes from the main branch
          git pull origin main 
          
          # Install any new dependencies
          pnpm install
          
          # Build the project for production
          pnpm run build
          
          # Reload the app with PM2 for zero-downtime update
          sudo systemctl restart averra